all: eseguibile

sum_difference_of_two_numbers.o: sum_difference_of_two_numbers.c
	gcc -c sum_difference_of_two_numbers.c

eseguibile: sum_difference_of_two_numbers.o
	gcc -o eseguibile sum_difference_of_two_numbers.o

clean: 
	rm sum_difference_of_two_numbers.o eseguibile
